apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
  - name: app-container
    image: nginx:1.19
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/certs
      readOnly: true  # Best practice for secrets
  volumes:
  - name: secret-volume
    secret:
      secretName: tls-secret
      defaultMode: 0400  # Read-only for owner
