apiVersion: v1
kind: Pod
metadata:
  name: projected-volume-pod
spec:
  containers:
  - name: app-container
    image: nginx:1.19
    volumeMounts:
    - name: projected-config
      mountPath: /etc/projected
      readOnly: true
  volumes:
  - name: projected-config
    projected:
      sources:
      - configMap:
          name: app-config
      - secret:
          name: db-credentials
          items:
          - key: username
            path: db/username
            mode: 0400
          - key: password
            path: db/password
            mode: 0400
      - downwardAPI:
          items:
          - path: "pod-name"
            fieldRef:
              fieldPath: metadata.name
