# Simple Web App v1 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v1
  namespace: canary-demo
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/version: v1.0
    deployment-type: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/version: v1.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
        app.kubernetes.io/version: v1.0
        deployment-type: stable
    spec:
      containers:
      - name: webapp
        image: nginx:1.20-alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: html-content
        configMap:
          name: webapp-v1-content